### ISSUE TITLE
Kubernetes monitoring guide

### ISSUE THREAD

**Issue by sugun999** [coreos/kube-prometheus#36] opened 2017-02-08 15:52 UTC
Hi,

I have setup kubernetes with coreOS by following below doc and the setup is perfectly fine.

https://coreos.com/kubernetes/docs/latest/getting-started.html

 Now I would like to monitor kubernetes objects(pods,services etc..). Is there step-by-step instruction guide?

I searched for proper guide but none worked for me. Show this error.

![error](https://cloud.githubusercontent.com/assets/24804615/22744809/3306bf72-ee27-11e6-9866-d2f66ead18e9.PNG)

**Comment by fabxc** [comment] 2017-02-09 17:47
Dupe of prometheus/prometheus#2405. Same maintainers over here and there, so closing this one.

**Closed by fabxc** 2017-02-09 17:47 UTC
