### ISSUE TITLE
Teardown does not remove StatefulSet for prometheus-frontend

### ISSUE THREAD

**Issue by one000mph** [coreos/kube-prometheus#32] opened 2017-01-19 20:29 UTC
The executable `hack/example-service-monitoring/teardown` leaves prometheus-frontend the StatefulSet in place. I needed to run `kubectl delete statefulset prometheus-frontend` to clean up.

**Comment by brancz** [comment] 2017-01-24 15:42
I am not able to reproduce this. Can you confirm that you can? And also provide us with the type of cluster (minikube, kops, bootkube, tectonic-installer, etc.), cluster version and kubectl version? Thanks! 🙂

**Comment by brancz** [comment] 2017-02-28 15:07
With current master of this repository are you able to reproduce this?

**Comment by one000mph** [comment] 2017-03-02 00:11
This appears to be resolved now. Thanks for checking in again.

**Comment by one000mph** [comment] 2017-03-02 00:13
The cluster was up'd with Stackpoint.io running k8s 1.5.1.
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brancz** [comment] 2017-03-02 08:16
Awesome! :slightly_smiling_face: Then I'll close this.

**Closed by brancz** 2017-03-02 08:16 UTC
